version: '3.9'

services:

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  backend:
    build: ./backend
    ports:
      - "8000:8000"

  payments:
    build: ./payments-service
    ports:
      - "9000:9000"